### ISSUE TITLE
Downloading a layer with quick filter causes an error

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geonode-mapstore-client#573]
If the qiuck filter is enabled on the attribute table the download will not work.

Error on console:

><?xml version="1.0" encoding="UTF-8"?><wps:ExecuteResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="https://development.demo.geonode.org/gs/ows?" version="1.0.0"><wps:Process wps:processVersion="1.0.0"><ows:Identifier>gs:DownloadEstimator</ows:Identifier><ows:Title>Estimator Process</ows:Title><ows:Abstract>Checks if the input file does not exceed the limits</ows:Abstract></wps:Process><wps:Status creationTime="2021-11-05T12:07:20Z"><wps:ProcessFailed><ows:ExceptionReport version="1.1.0"><ows:Exception exceptionCode="NoApplicableCode"><ows:ExceptionText>Failed to retrieve value for input filter
Parsing failed for PropertyIsLike: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
java.lang.String cannot be cast to java.lang.Boolean</ows:ExceptionText></ows:Exception></ows:ExceptionReport></wps:ProcessFailed></wps:Status></wps:ExecuteResponse>

**How to reproduce**
- Use [this layer](https://development.demo.geonode.org/layers/geonode_demo_data:geonode:ne_10m_roads)
Follows the steps on the gif below:
![1.gif](https://images.zenhubusercontent.com/5da5b30f66de7b0001e4e77c/e1796767-dc5b-4e75-a114-445cf14d85ae)

## Other useful  informations

On GeoNode 3.3.0 and 3.2.2

---

@ElenaGallo commented on [Fri Nov 05 2021](https://github.com/geosolutions-it/geonode/issues/1040#issuecomment-961859565)

@simboss here the issue of filtered download bug

**Comment by giohappy** [comment]
This is probably [fixed in MapStore](https://github.com/geosolutions-it/MapStore2/commit/510d68c303026fd9035e2d933dabe789a8e88984) but the commit has not been ported back yet.

@allyoucanmap please make a check to confirm if this is the same problem, and let's port the fix to geonode 3.3.x (and master).

**Comment by AleMScof** [comment]
Hi guys,

this PR should be backported on 3.2.x as well.

A-

**Comment by allyoucanmap** [comment]
this fix has been ported on all branches: master, 3.3.x and 3.2.x

**Comment by rmkw** [comment]
This error is due to the allowed download size by Geoserver. The default allowed size is 50 MB. I changed it to 5 GB but I am still getting the same error. What can I do? Help.
![image](https://github.com/GeoNode/geonode-mapstore-client/assets/55543994/f4f9c05d-797a-4d51-bf0d-9daa21051695)
![image](https://github.com/GeoNode/geonode-mapstore-client/assets/55543994/51df4a8c-6c7c-41de-ac99-46030ec506d0)

**Comment by giohappy** [comment]
Have you increased both the `writeLimits` and the `hardOutputLimit`?

**Comment by rmkw** [comment]
![image](https://github.com/GeoNode/geonode-mapstore-client/assets/55543994/a0620a23-8443-4ba9-a76f-77ad8152ccff)

YES, Yes, but I don't know if I did it right, I set the value to 5GB.

**Comment by giohappy** [comment]
@rmkw is it a vector or a raster dataset?
